-- Migration 024 — executive_digests
--
-- The weekly chief-of-staff Friday memo. Synthesises 7 days of signals
-- (relationship shifts, forgotten loops, commitments, meetings) into a
-- short executive narrative the user can read in 60 seconds.
--
-- Daily briefings already exist (`daily_briefings`); this is the weekly
-- complement with a different prompt, a different audience for the user's
-- attention (it's a memo, not a task list), and one-row-per-week storage.
--
-- One row per (user_id, week_starting). `week_starting` is the Monday ISO
-- date so the same week always collides regardless of which day the cron
-- fires. The cron upserts on conflict — re-runnable for the same week
-- without producing duplicates.

create table if not exists public.executive_digests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  week_starting date not null,
  payload jsonb not null,
  markdown text not null,
  model text,
  generated_at timestamptz not null default now(),
  unique (user_id, week_starting)
);

create index if not exists executive_digests_user_week_idx
  on public.executive_digests (user_id, week_starting desc);

alter table public.executive_digests enable row level security;

drop policy if exists "users read own digests" on public.executive_digests;
create policy "users read own digests"
  on public.executive_digests
  for select
  using (auth.uid() = user_id);

-- Writes are service-role only (the cron uses the service key). No
-- end-user INSERT/UPDATE — users can only read their own.

comment on table public.executive_digests is
  'Weekly chief-of-staff memo. One row per (user, week). Generated by the executive-digest cron on Fridays.';
